// S06 CHECKLIST 06: the manager upload (POST /api/manager/recordings), against
// the real local test database (MIGRATION_TEST_DB_NAME). Runs only when that
// variable is set.
//
// Nothing real is uploaded here. The "recording" is a silent WAV generated in
// this file — a few hundred bytes of invented audio — and it is written into a
// throw-away MEDIA_ROOT under the OS temp folder, never inside the repo. The
// stage, the accounts and the rows this suite creates are removed afterwards.
import { readFile, mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import request from 'supertest';
import { afterAll, describe, expect, it } from 'vitest';
import type { ManagerUploadResponse } from '@fac-academy/shared';
import type { QuestionGenJob, TranscriptionJob } from '../../src/jobs/mediaJobs.js';
import { createLocalMediaStore } from '../../src/media/store.js';
import { QUEUE_NAMES } from '../../src/queues/names.js';
import { createInMemoryQueue } from '../../src/queues/queue.js';
import type { InMemoryJobQueue } from '../../src/queues/queue.js';
import { TEST_DB, auditRows, openTestDb, signIn } from './helpers/authHarness.js';
import type { Db, Harness, SignedIn } from './helpers/authHarness.js';

/** A silent 16-bit mono WAV: `seconds` long, and tiny. Invented content. */
function makeWav(seconds: number, sampleRate = 200): Buffer {
  const dataSize = seconds * sampleRate * 2;
  const buf = Buffer.alloc(44 + dataSize);
  buf.write('RIFF', 0);
  buf.writeUInt32LE(36 + dataSize, 4);
  buf.write('WAVE', 8);
  buf.write('fmt ', 12);
  buf.writeUInt32LE(16, 16);
  buf.writeUInt16LE(1, 20); // PCM
  buf.writeUInt16LE(1, 22); // mono
  buf.writeUInt32LE(sampleRate, 24);
  buf.writeUInt32LE(sampleRate * 2, 28);
  buf.writeUInt16LE(2, 32);
  buf.writeUInt16LE(16, 34);
  buf.write('data', 36);
  buf.writeUInt32LE(dataSize, 40);
  return buf;
}

const MAX_UPLOAD_BYTES = 8 * 1024;

let database: Db | null = null;
if (TEST_DB === '') {
  console.warn('[media-upload.test] MIGRATION_TEST_DB_NAME is not set: skipping the upload tests.');
} else {
  try {
    database = await openTestDb();
  } catch (err) {
    console.warn(`[media-upload.test] test database unavailable: ${(err as Error).message}`);
  }
}

describe.skipIf(database === null)('S06 manager upload (test DB)', async () => {
  const db = database!;
  const mediaRoot = await mkdtemp(path.join(tmpdir(), 'academy-media-test-'));
  const store = createLocalMediaStore(mediaRoot);
  const stageCode = `zzmedia${db.tag}`;
  let stageId = '';

  // A stage of this suite's own, so nothing depends on the seeded content.
  {
    const { rows } = await db.pool.query<{ id: string }>(
      `INSERT INTO academy.stages (code, level_id, position, title, blurb, track, display_num)
       VALUES ($1,
               (SELECT id FROM academy.levels ORDER BY id LIMIT 1),
               (SELECT COALESCE(max(position), 0) + 1 FROM academy.stages
                 WHERE level_id = (SELECT id FROM academy.levels ORDER BY id LIMIT 1)),
               'Media upload test stage', 'Created by media-upload.test.ts', 'FULL', 'T')
       RETURNING id::text AS id`,
      [stageCode],
    );
    stageId = rows[0]!.id;
  }

  afterAll(async () => {
    await db.pool.query('DELETE FROM academy.call_recordings WHERE stage_id = $1', [stageId]);
    await db.pool.query('DELETE FROM academy.stages WHERE id = $1', [stageId]);
    await db.cleanup();
    await rm(mediaRoot, { recursive: true, force: true });
  });

  function setup(): { h: Harness; queue: InMemoryJobQueue } {
    const queue = createInMemoryQueue();
    const h = db.harness({
      mediaStore: store,
      mediaUpload: { queue, maxUploadBytes: MAX_UPLOAD_BYTES },
    });
    return { h, queue };
  }

  const manager = (h: Harness): Promise<SignedIn> =>
    signIn(h, h.crm.add(db.newAccount({ role: 'Management' })));
  const staff = (h: Harness): Promise<SignedIn> =>
    signIn(h, h.crm.add(db.newAccount({ role: 'Sales' })));

  function upload(
    h: Harness,
    who: SignedIn,
    body: Buffer,
    opts: { contentType?: string; title?: string; stage?: string; description?: string } = {},
  ) {
    const query = new URLSearchParams({
      stageCode: opts.stage ?? stageCode,
      title: opts.title ?? 'Invented training call',
      description: opts.description ?? 'Generated by the test suite',
    });
    return request(h.app)
      .post(`/api/manager/recordings?${query.toString()}`)
      .set('Cookie', who.cookie)
      .set('Content-Type', opts.contentType ?? 'audio/wav')
      .send(body);
  }

  it('staff get 403; not signed in gets 401', async () => {
    const { h } = setup();
    const who = await staff(h);
    const res = await upload(h, who, makeWav(1));
    expect(res.status).toBe(403);
    expect(res.body).toEqual({ error: 'forbidden' });

    const anon = await request(h.app)
      .post(`/api/manager/recordings?stageCode=${stageCode}&title=x`)
      .set('Content-Type', 'audio/wav')
      .send(makeWav(1));
    expect(anon.status).toBe(401);
  });

  it('a manager upload lands on disk, in the database, in the audit log and on both queues', async () => {
    const { h, queue } = setup();
    const mgr = await manager(h);
    const wav = makeWav(2);

    const res = await upload(h, mgr, wav, { title: 'Offer and payment call' });
    expect(res.status).toBe(201);
    const body = res.body as ManagerUploadResponse;
    expect(body.byteSize).toBe(wav.byteLength);
    expect(body.durationSecs).toBe(2);
    expect(body.contentType).toBe('audio/wav');
    expect(body.mediaKey).toMatch(/^academy\/media\/offer-and-payment-call-[0-9a-f]{8}\.wav$/);

    // The bytes really are on disk, unchanged.
    const onDisk = await readFile(path.join(mediaRoot, body.mediaKey));
    expect(onDisk.equals(wav)).toBe(true);

    const { rows } = await db.pool.query<{
      stage_id: string;
      title: string;
      media_key: string;
      media_type: string;
      duration_secs: number;
      byte_size: string;
      content_type: string;
      checksum_sha256: string;
      uploaded_by: string;
      transcript_status: string;
    }>(
      `SELECT stage_id::text AS stage_id, title, media_key, media_type, duration_secs,
              byte_size::text AS byte_size, content_type, checksum_sha256,
              uploaded_by::text AS uploaded_by, transcript_status
         FROM academy.call_recordings WHERE id = $1`,
      [body.recordingId],
    );
    const row = rows[0]!;
    expect(row.stage_id).toBe(stageId);
    expect(row.title).toBe('Offer and payment call');
    expect(row.media_key).toBe(body.mediaKey);
    expect(row.media_type).toBe('AUDIO');
    expect(row.duration_secs).toBe(2);
    expect(row.byte_size).toBe(String(wav.byteLength));
    expect(row.content_type).toBe('audio/wav');
    expect(row.checksum_sha256).toMatch(/^[0-9a-f]{64}$/);
    expect(row.uploaded_by).toBe(String(mgr.me.id));
    expect(row.transcript_status).toBe('PENDING');

    const audit = await auditRows(db.pool, { traineeId: mgr.me.id, eventType: 'MEDIA_UPLOADED' });
    expect(audit).toHaveLength(1);
    expect(audit[0]!.actor).toBe(`manager:${mgr.me.id}`);
    expect(audit[0]!.payload).toMatchObject({
      recordingId: body.recordingId,
      stage: stageCode,
      mediaKey: body.mediaKey,
      byteSize: wav.byteLength,
      durationSecs: 2,
    });

    // Two jobs, ids only, with the new recordingId.
    expect(queue.jobs).toHaveLength(2);
    const [transcription] = queue.jobsOn<TranscriptionJob>(QUEUE_NAMES.transcription);
    expect(transcription?.name).toBe('transcribe');
    expect(transcription?.data).toEqual({
      recordingId: body.recordingId,
      mediaKey: body.mediaKey,
      contentType: 'audio/wav',
      durationSecs: 2,
    });
    const [questions] = queue.jobsOn<QuestionGenJob>(QUEUE_NAMES.questionGen);
    expect(questions?.name).toBe('draft-questions');
    expect(questions?.data).toEqual({
      recordingId: body.recordingId,
      stageId: Number(stageId),
      approvalState: 'DRAFT',
    });
    // Nothing that could name a person is in either payload.
    expect(JSON.stringify(queue.jobs)).not.toContain('@example.com');
  });

  it('an oversize upload is 413 and nothing is written', async () => {
    const { h, queue } = setup();
    const mgr = await manager(h);
    const before = await countRecordings(db, stageId);

    const res = await upload(h, mgr, makeWav(1, 8_000), { title: 'Far too long' });
    expect(res.status).toBe(413);
    expect(res.body).toEqual({ error: 'too_large' });
    expect(await countRecordings(db, stageId)).toBe(before);
    expect(queue.jobs).toHaveLength(0);
  });

  it('an unsupported type is 415, and so are bytes that are not what they claim', async () => {
    const { h, queue } = setup();
    const mgr = await manager(h);

    const wrongType = await upload(h, mgr, Buffer.from('%PDF-1.7 not a recording'), {
      contentType: 'application/pdf',
    });
    expect(wrongType.status).toBe(415);
    expect(wrongType.body).toEqual({ error: 'unsupported_type' });

    const notAudio = await upload(h, mgr, Buffer.alloc(300, 0x41), { contentType: 'audio/wav' });
    expect(notAudio.status).toBe(415);
    expect(queue.jobs).toHaveLength(0);
  });

  it('a bad stage code or a missing title is a 400/404, not a 500', async () => {
    const { h } = setup();
    const mgr = await manager(h);

    const noTitle = await request(h.app)
      .post(`/api/manager/recordings?stageCode=${stageCode}`)
      .set('Cookie', mgr.cookie)
      .set('Content-Type', 'audio/wav')
      .send(makeWav(1));
    expect(noTitle.status).toBe(400);
    expect(noTitle.body).toEqual({ error: 'invalid_request' });

    const unknownStage = await upload(h, mgr, makeWav(1), { stage: 'no-such-stage' });
    expect(unknownStage.status).toBe(404);
    expect(unknownStage.body).toEqual({ error: 'not_found' });
  });

  it('is 503 while ACADEMY_V2 is off', async () => {
    const queue = createInMemoryQueue();
    const h = db.harness({
      flagEnabled: false,
      mediaStore: store,
      mediaUpload: { queue, maxUploadBytes: MAX_UPLOAD_BYTES },
    });
    const res = await request(h.app)
      .post(`/api/manager/recordings?stageCode=${stageCode}&title=x`)
      .set('Content-Type', 'audio/wav')
      .send(makeWav(1));
    expect(res.status).toBe(503);
    expect(res.body).toEqual({ flag: 'off' });
  });
});

async function countRecordings(db: Db, stageId: string): Promise<number> {
  const { rows } = await db.pool.query<{ n: string }>(
    'SELECT count(*)::text AS n FROM academy.call_recordings WHERE stage_id = $1',
    [stageId],
  );
  return Number(rows[0]!.n);
}
